version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        progress: plain
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    ports:
      - 3000:3000
      - 5173:5173
    stdin_open: true
    tty: true
    command: bash -c "bun install && bun run build && bun run dev"
